spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1
            minimum-idle: 1
            maximum-pool-size: 10
            pool-name: HikariCP
            auto-commit: false    
            connection-timeout: 30000
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        type: com.zaxxer.hikari.HikariDataSource
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

        