services:
  # volume é por container - dados persistidos
  postgre:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}

    volumes:
      # arquivo sql para criar o DATABASE/SCHEMA
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # tipo gerenciado pelo doker
      - data_vol:/var/lib/postgresql/data
    networks:
      - compose-net
  
volumes:
  data_vol:

networks:
  compose-net:
    driver: bridge
